### ISSUE TITLE
AIU discount code doesn't work.

### ISSUE THREAD

**Issue by wammar** [higgood/seechat-folks#44] opened 2024-07-02 06:34 UTC
**Context**
AIU students should be able to get a significant discount using [this coupon code](https://www.notion.so/higg/SeeChat-x-Ideas-61c0c1e1cfbc4a208f4a0886de8d0325?pvs=4#37a811e5a8da4af198e03ead0baacd0c).

**Describe the bug**
Coupon doesn't work at checkout.

**[Required] Where did you encounter the bug**
[ ] While creating your account (first time user)
[ ] While logging in to your account
[x] While applying changes to the settings (e.g., # of papers)
[ ] While typing the query
[ ] While Idea Factory was thinking or generating text
[ ] After Idea Factory was done generating text

**[Required] Reality vs. Expectation**
Reality: User have to pay $10
Expectation: User have to pay $2

**Screenshots**
![image](https://github.com/higgood/seechat-folks/assets/1858803/8d635e9d-fd11-4351-986c-f39e43a4a0dd)

**Desktop (if applicable):**
 - OS:  Windows 11
 - Browser Edge

Thank you for improving the Idea Factory!!

**Comment by wammar** [comment] 2024-07-02 06:37
Relevant [slack discussion](https://thinksparkgroup.slack.com/archives/C06RPNGAAQJ/p1719902109910709) (only accessible to HIGG team members).

**Comment by muhammadnasr** [comment] 2024-07-02 14:30
@wammar you need to create coupons in production stripe as mentioned in this issue
https://github.com/orgs/higgood/projects/1/views/6?filterQuery=milestone%3AJune2024+coup&pane=issue&itemId=68553001

**Comment by muhammadnasr** [comment] 2024-07-04 19:06
Duplicate of [#228](https://github.com/higgood/seechat_backend/issues/228)

**Closed by muhammadnasr** 2024-07-04 19:06 UTC
Labels: bug
